### ISSUE TITLE
whereとwhenが""（空白）だったら、保存できないようにしたい

### ISSUE THREAD

**Issue by ryo24** [sakurafurafoop/date#2]
tableViewに空白行が生まれるとわかりづらい

**Comment by ryo24** [comment]
こういう感じになるので避けたい
<img width="327" alt="image" src="https://user-images.githubusercontent.com/9673470/37833170-0506971a-2eee-11e8-9385-4c3155432794.png">

**Comment by sakurafurafoop** [comment]
@ryo24 おうけいです！

**Comment by sakurafurafoop** [comment]
whereが空欄の場合のみ保存できない
whenが空欄でも大丈夫（なぜならこれから行きたいものはwhenをまだ登録できないから）
